### ISSUE TITLE
Error using Master

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2112]
![image](https://user-images.githubusercontent.com/34346751/44845978-fb4d2980-ac1c-11e8-84c5-f19df118c7f9.png)

Using Master that was mentioned to stop the updating powershell issue.  This is what I keep getting.  I manually filled in wallet address in config.txt to test and then it ran, but of course not with mining pool hub because no worker name. They have only ever been in start.bat.  I usually copy some things over  so I just tested with whatever was unzipped right now.  Still same thing.

**Comment by thebeerbaron2018** [comment]
Verified.  Getting the same.

**Comment by UselessGuru** [comment]
This has been reported before, but I could note reproduce it. 
Could you please post the start batch file as well as the config file. TIA!

**Comment by robl45** [comment]
There is literally nothing to post.  Mine did it with the stock unzipped contents.  The start file is exactly what is in the zip.  The config.txt is whatever gets created.

**Comment by thebeerbaron2018** [comment]
If I fill out the UserName and Wallet in the config.txt then it seems to work.  It doesn't appear to be picking up the username or wallet from the batch file regardless of what is there.  @UselessGuru as a test if you want to "force" the issue try just

 `@set "command=& .\multipoolminer.ps1`

in the batch file as that should (correctly) produce the error - if that's not working for you then you might have some different files - maybe unzip a brand new directory and try?  

I can produce it with the line above and then even if i fill out -Wallet and -UserName the error persists.

**Comment by thebeerbaron2018** [comment]
I think it might be something to do with the CmdletBinding part of multipoolminer.ps1 (at the very beginning).  Could it be that the two new changes (ExcludeDeviceName and DisableDualMining) don't have aliases? Either that or there is a missing comma somewhere that's causing the block to not read all the values? Scratching head here

**Comment by thebeerbaron2018** [comment]
Or maybe in the block 165-172 where it loads the config - maybe the changes there have affected the load?

**Comment by thebeerbaron2018** [comment]
That appears to work on first run (when there is no config) but fails on second run with 

`Write-Log : .\Config.txt is invalid. Cannot continue.
At C:\Users\miner\Desktop\MultiPoolMiner-MultipoolMiner_FullyMerged\MultiPoolMiner.ps1:179 char:9
+         Write-Log -Level Error "$($ConfigFile) is invalid. Cannot con ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log`

**Comment by thebeerbaron2018** [comment]
I assume I put your change in the right place???

`while ($true) {
    $ConfigBackup = $Config
    #Load the config, read command line parameters except ConfigFile, use default values for those that are not in command line
    $Parameters = @{}

    $MyInvocation.MyCommand.Parameters.Keys | Where-Object {$_ -ne "ConfigFile"} | ForEach-Object {
        $Parameters.Add($_ , (Get-Variable $_ -ValueOnly -ErrorAction SilentlyContinue))
    }

    #Config file may not contain an entry for all supported parameters, use value from command line, or if empty use default
    $Config | Add-Member Pools ([PSCustomObject]@{}) -ErrorAction SilentlyContinue
    $Config | Add-Member Miners ([PSCustomObject]@{}) -ErrorAction SilentlyContinue
    $PSBoundParameters.Keys | Where-Object {$_ -ne "ConfigFile"} | ForEach-Object {
        if (Get-Variable $_ -ValueOnly -ErrorAction SilentlyContinue) {
            $Config | Add-member $_ (Get-Variable $_ -ValueOnly -ErrorAction SilentlyContinue) -ErrorAction SilentlyContinue
        }
    }`

**Comment by UselessGuru** [comment]
> I assume I put your change in the right place???

Yes 👍

**Comment by thebeerbaron2018** [comment]
Then I am getting the config error on second run then :) lol

Also .... on first run (when it works) am getting this spammed after "no pools available"

```
Cannot convert argument "value", with value: "$Interval", for "AddSeconds" to type "System.Double": "Cannot convert value "$Interval" to type
"System.Double". Error: "Input string was not in a correct format.""
At C:\Users\miner\Desktop\MultiPoolMiner-MultipoolMiner_FullyMerged\MultiPoolMiner.ps1:243 char:5
+     $StatEnd = $Timer.AddSeconds($Config.Interval)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
```

**Comment by thebeerbaron2018** [comment]
And then (which I think is also to do with it).... 

```
Start-Sleep : Cannot bind parameter 'Seconds'. Cannot convert value "$Interval" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\miner\Desktop\MultiPoolMiner-MultipoolMiner_FullyMerged\MultiPoolMiner.ps1:320 char:21
+         Start-Sleep $Config.Interval
+                     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-Sleep], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.StartSleepCommand

Cannot convert argument "value", with value: "$Interval", for "AddSeconds" to type "System.Double": "Cannot convert value "$Interval" to type
"System.Double". Error: "Input string was not in a correct format.""
At C:\Users\miner\Desktop\MultiPoolMiner-MultipoolMiner_FullyMerged\MultiPoolMiner.ps1:243 char:5
+     $StatEnd = $Timer.AddSeconds($Config.Interval)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
```

**Comment by thebeerbaron2018** [comment]
I assume this error is due to interval being blank in the start.bat and not specified in the config.txt - although why it is then not using the default of 60 from the top of multipoolminer.ps1 - ahhhh - seems that your new code changes it to "" if not specified on start.bat or in config.txt!!!

**Comment by thebeerbaron2018** [comment]
OK downloaded the TXT file you attached and that fixed the config error on second run.... also fixed the $Interval problem too :)  Good Job.

**Comment by thebeerbaron2018** [comment]
(I think the $Interval errors were due to me putting your 'fix' code into the file at the wrong place) My bad.

**Comment by UselessGuru** [comment]
> (I think the $Interval errors were due to me putting your 'fix' code into the file at the wrong place) My bad.

There was a possible problem if -Interval (or any other parameter that requires a value to be present) was not present in neiter the command line or hard configured in the config.file.

Please test the attached file:

[MultiPoolMiner_ps1.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2336344/MultiPoolMiner_ps1.txt)

MultipoolMiner.ps1 line 166 has changed:

`    $MyInvocation.MyCommand.Parameters.Keys | Where-Object {$_ -ne "ConfigFile" -and -not $Config.$_} | ForEach-Object {`

**Comment by thebeerbaron2018** [comment]
Yeah that's what I was trying to say in a roundabout scatty kind of way :)
Does this take into consideration that if not in the start.bat AND not in the config.txt THEN check for a default value BEFORE assigning ""

**Comment by UselessGuru** [comment]
> Does this take into consideration that if not in the start.bat AND not in the config.txt THEN check for a default value BEFORE assigning ""

Here's the magic explained:

- for all required available parameters there is a default hard coded value (MultiPoolMiner.ps1 (Lines 5 - 74)
- the notable exceptions are Wallet & UserName. We cannot put default values because they define where the money goes. No values -> error message

- for optional parameters there is no default value, they remain empty

- On first program start:
Powershell reads the command line parameters and assigns the variables (e.g. -Wallet xyz -> $Wallet = xyz).
 Command line parameter values will take precedence over the hard coded default value
-> this is how you get meaningful variable values

If config file does not yet exist MPM creates the config file named $ConfigFile (remember the command line parameter with the same name?). 
Note: this will NOT contain any hard coded config values, just references to other variable (note the beginning $)
```:
{
    "VersionCompatibility":  "3",
    "Wallet":  "$Wallet",
    "UserName":  "$UserName",
    "WorkerName":  "$WorkerName",
    "API_ID":  "$API_ID",
    "API_Key":  "$API_Key",
    "Interval":  "$Interval",
    "Region":  "$Region",
    "SSL":  "$SSL",
    "DeviceName":  "$DeviceName",
    "Algorithm":  "$Algorithm",
    "MinerName":  "$MinerName",
    "PoolName":  "$PoolName",
    "ExcludeAlgorithm":  "$ExcludeAlgorithm",
    "ExcludeMinerName":  "$ExcludeMinerName",
    "ExcludePoolName":  "$ExcludePoolName",
    "DisableDualMining":  "$DisableDualMining",
    "Currency":  "$Currency",
    "Donate":  "$Donate",
    "Proxy":  "$Proxy",
    "Delay":  "$Delay",
    "Watchdog":  "$Watchdog",
    "MinerStatusUrl":  "$MinerStatusUrl",
    "MinerStatusKey":  "$MinerStatusKey",
    "SwitchingPrevention":  "$SwitchingPrevention",
    "ShowMinerWindow":  "$ShowMinerWindow",
    "UseFastestMinerPerAlgoOnly":  "$UseFastestMinerPerAlgoOnly",
    "IgnoreCosts":  "$IgnoreCosts",
    "ShowPoolBalances":  "$ShowPoolBalances",
    "ShowPoolBalancesExcludedPools":  "$ShowPoolBalancesExcludedPools",
    "Pools":  {

              },
    "Miners":  {

               }
}

```
- For each loop:
MPM reads the config file and stores it as $Config 

For each available command line parameter (lines 5-74): If Config.[ParameterName] is $null MPM will substitute the value with the variable value xxx (lines 166-170)

You can check the complete config data set at http://localhost:3999/runningconfig.html

**Comment by thebeerbaron2018** [comment]
Yeah I understand that - the way I read it before was that it was checking the command line, then checking config.txt and if not found was assigning "".  I was just checking that say in the case of $Interval where there was nothing on the command line and nothing in config.txt that your code wouldn't overwrite the default of 60 from the defined ones at the beginning of the file with "" - my PS skills are shady at best :) gimme Python any day :)

**Comment by UselessGuru** [comment]
@thebeerbaron2018 

Does the last fix work for you? If so could you open a PR for it (so Grant & I can approve it)? Thank you very much!

**Comment by thebeerbaron2018** [comment]
Sorry, yes it works - I was to explain myself a little clearer before even though you got what I meant.  I was just making sure that the code you added didn't overwrite the default values with "" if they aren't present on the command line or in the config.txt - I was away from the machines so I couldn't test - but have done so now.... removed all parameters from start.bat except wallet and username, made sure no config.txt present - run miner > result is that $Interval is still set to the default of 60 as it should be.  All is well!

**Comment by UselessGuru** [comment]
@thebeerbaron2018 

Please open a PR for the fix - Grant & I can then approve it (while Aaron is not on it).

**Comment by thebeerbaron2018** [comment]
Sorry I don't use github that much and only from my phone. Wouldn't want to create something and mess it up by mistake.

**Comment by robl45** [comment]
Did new file attached here and dropped in log as well as pasted in issue.
[MultiPoolMiner_2018-08-30_21-20-52.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2338492/MultiPoolMiner_2018-08-30_21-20-52.txt)
, That made it start but something is not quite right.
As you can see its not getting the algorithm in the host name and its not getting the password right either.  I switched back to the fully merged version and it works perfectly again.

NFO: Starting miner (CcminerZealot): 'C:\Users\Rob\Downloads\MultiPoolMiner-master (1)\MultiPoolMiner-master\Bin\NVIDIA-Zealot\z-enemy.exe -a sonoa -o stratum+tcp://mine.zergpool.com:8733 -u XXXXXXXXXXXKXihwghJyK1nE2 -p ,c=LTC'
PS>TerminatingError(Start-SubProcess): "Exception calling "Create" with "1" argument(s): "At line:1 char:355
+ ... .zergpool.com:8733 -u XXXXXXXXXXXXXXXpCKXihwghJyK1nE2 -p ,c=LTC *> ...
+                                                                 ~
Missing argument in parameter list.""
Start-SubProcess : Exception calling "Create" with "1" argument(s): "At line:1 char:355
+ ... .zergpool.com:8733 -u XXXXXXXXXXXXXuUpCKXihwghJyK1nE2 -p ,c=LTC *> ...

**Comment by UselessGuru** [comment]
@thebeerbaron2018 

>  Wouldn't want to create something and mess it up by mistake.

You can't mess it up because 2 people with write access have to verify it first....

**Comment by UselessGuru** [comment]
@robl45 

Thank you for your feedback!

What do you have configured as '-WorkerName'? It appears to be empty.
Please post your start bat as well as the output of http://localhost:3999/config.

Does the error happen only with ZergPool, or with other pools too?

In any case ZergPool needs an update. Please try
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2049

**Comment by robl45** [comment]
Information pasted below, it seems to be specific to Zergpool which I use LTC as specified in the config.  I used the zergpool file that I been using with the fully merged.  That does the hostname correctly but still the -p field is messed up and it is not mining on zergpool.  config.txt and start.bat attached.

[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2339714/Config.txt)

[Start.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2339716/Start.zip)

{
  "VersionCompatibility": "3",
  "Wallet": "1GJDZKUFLeJfWaDeCRXTBC656vtkjeULoX",
  "UserName": "robminer",
  "WorkerName": "rob",
  "API_ID": 0,
  "API_Key": "",
  "Interval": 60,
  "Region": "US",
  "SSL": {
    "IsPresent": false
  },
  "DeviceName": "nvidia",
  "Algorithm": null,
  "MinerName": null,
  "PoolName": [
    "miningpoolhub",
    "zpool",
    "hashrefinery",
    "zergpool",
    "ahashpool"
  ],
  "ExcludeAlgorithm": null,
  "ExcludeMinerName": null,
  "ExcludePoolName": null,
  "Currency": [
    "BTC",
    "USD"
  ],
  "Donate": 0,
  "Proxy": "",
  "Delay": 0,
  "Watchdog": {
    "IsPresent": true
  },
  "MinerStatusUrl": "https://multipoolminer.io/monitor/miner.php",
  "MinerStatusKey": "1GJDZKUFLeJfWaDeCRXTBC656vtkjeULoX",
  "SwitchingPrevention": 2.0,
  "DisableAutoUpdate": null,
  "ShowMinerWindow": {
    "IsPresent": false
  },
  "UseFastestMinerPerAlgoOnly": {
    "IsPresent": false
  },
  "IgnoreCosts": {
    "IsPresent": false
  },
  "ShowPoolBalances": {
    "IsPresent": false
  },
  "ShowPoolBalancesExcludedPools": {
    "IsPresent": false
  },
  "Pools": {
    "zergpool": {
      "LTC": "LeTUNYViANaPTypGuUpCKXihwghJyK1nE2",
      "worker": "rob"
    },
    "Miners": {},
    "Hashrefinery": {
      "BTC": "1GJDZKUFLeJfWaDeCRXTBC656vtkjeULoX",
      "User": "robminer",
      "Worker": "rob",
      "API_ID": 0,
      "API_Key": ""
    },
    "MiningPoolHub": {
      "BTC": "1GJDZKUFLeJfWaDeCRXTBC656vtkjeULoX",
      "User": "robminer",
      "Worker": "rob",
      "API_ID": 0,
      "API_Key": ""
    }
  },
  "Miners": {},
  "DisableDualMining": {
    "IsPresent": false
  }
}

**Comment by UselessGuru** [comment]
@robl45 

Strange - your config looks fine, except that for zergpool 'worker' is all small letters. But I doubt that this is causing issues (you better change this to 'Worker').

Please note that this morning I specifically pdated ZergPool (also in _FullyMerged) - it had a problem exactly in the area where you have the issue.

Please try this:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2049

**Comment by robl45** [comment]
The config and start.bat are straight from fully merged. As is the zergpool
file.   My guess is it's in include or the multipoolminer.ps1

**Comment by UselessGuru** [comment]
The pool section in the config file must have been edited manually, otherwise there it would not say ```
"zergpool": {
"LTC": "LeTUNYViANaPTypGuUpCKXihwghJyK1nE2",
"worker": "rob"
},
```

Let me know about the finding with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2049

**Comment by robl45** [comment]
Yes I edited that to use ltc with zergpool and that is directly copied from
fully merged

**Comment by UselessGuru** [comment]
@robl45:

I've looked at you config - it's not ok. Here is the fixed version:

[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2341820/Config.txt)

But this is not the problem :-(

Github is playing tricks here, because the content of https://github.com/MultiPoolMiner/MultiPoolMiner/archive/MultipoolMiner_FullyMerged.zip is not identical to what the latest master + all the fixes should be (reason: github cannot automatically merge 4 files). 👎 

Hopefully this is fixed now - can you try with a new download and the attached config?

**Comment by robl45** [comment]
So download a new master and try this config?

**Comment by robl45** [comment]
So I did as instructed.  It works but it only brings up zergpool and only a
few algorithms.

**Comment by thebeerbaron2018** [comment]
@robl45 Yes it will look like that at first run because only one miner will have been downloaded the rest won't have been downloaded yet.  Let it download everything and then stop and restart the program and you should see all the algorithms benchmarking

**Comment by thebeerbaron2018** [comment]
@UselessGuru  there is still an issue with those new lines of code that you added around 159-170.  It can be demonstrated as I was trying to explain before like this : if you do NOT have the "-delay xx" set in start.bat AND you do NOT have Delay : "xx" set in the config file then delay SHOULD be 0 as set in the defaults.... but it's not.... and line 583 (Start-Sleep $Config.Delay) will fail saying that Delay is null.  So your code must be overwriting the default of 0 with ""

**Comment by robl45** [comment]
I copied all bin from version I been using so everything was there.

**Comment by robl45** [comment]
This is what I'm getting.
![image](https://user-images.githubusercontent.com/34346751/44961454-75acd080-aedf-11e8-8216-26438678b2ea.png)

Getting at least twice as many with the fully merged version and there are half as many miners in the BIN currently.

**Comment by UselessGuru** [comment]
> Getting at least twice as many with the fully merged version and there are half as many miners in the BIN currently.

I don't understand. What is the expected result?

**Comment by robl45** [comment]
I should be getting the same amount of algorithms and miners or somewhat
similar.   Not half as many.

**Comment by UselessGuru** [comment]
Did you notice the 'Unprofitable Algo' change? Could It be that only unprofitable algos are gone?
Maybe a before and after screenshot would shed some light...

**Comment by robl45** [comment]
This is fully merged.

As you can see, I can't even get all the algos and miners on the same snip.
![image](https://user-images.githubusercontent.com/34346751/45005382-04dde500-afc1-11e8-88e9-6c3b15f2bc2d.png)

**Comment by UselessGuru** [comment]
Did you notice that you no longer see duplicated entries per algorithm.
I assume you have enabled UseFastestMinerPerAlgoOnly.

**Comment by robl45** [comment]
So does this master appear to be working correctly from the screenshots I provided?   Should any of the options be changed in the config.txt?

**Comment by UselessGuru** [comment]
@robl

Sorry about the delay... the config file I sent you was causing issues.... my fault I fixed it (see attached file below). A freshly created default config file is not affected by this.

MPM interprets the definition of some config items not as expected, e.g.

```
  "UseFastestMinerPerAlgoOnly": {
    "IsPresent": false
  },
```

got interpreted as $true so UseFastestMinerPerAlgoOnly became activated and you only see the shorter algo list.

[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2354034/Config.txt)

**Comment by robl45** [comment]
Thanks much better, still not seeing any equihash variants with this one though.

**Comment by robl45** [comment]
I checked and the equihash miner EWBF.ps1 was not in the master.  it had EWBF.TXT.  That fixed the equihash issue.  Have not seen any of the updating powershell issues.  It still eventually eats up all the memory though.  I had like 121 powershell instances before I restarted just now.

**Comment by UselessGuru** [comment]
@robl45 

Is it ok to close this issue?

**Comment by robl45** [comment]
Yes.
